config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :branches
  resources :employees
  get 'home/index'
  devise_for :users

  root :to => 'home#index'


end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :employees
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:id_branch, :name, :address)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_with(model: branch, local: true) do |form| %>
  <% if branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
        <% branch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :id_branch %>
    <%= form.number_field :id_branch %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<div class="container margin-top">

  <div class="row">

    <div class="col-md-5 col-md-offset-3">
      <h1>Editing Branch</h1>
      <hr>

      <%= render 'form', branch: @branch %>

      <%= link_to 'Show', @branch %> |
      <%= link_to 'Back', branches_path %>
    </div>
  </div>


  </div>

</div>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>



<div class="container">

  <h1>Branches</h1>
  <hr>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Id branch</th>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.id_branch %></td>
        <td><%= branch.name %></td>
        <td><%= branch.address %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>
</div>

app/views/branches/new.html.erb
<div class="container margin-top">

  <div class="row">

    <div class="col-md-5 col-md-offset-3">
      <h1>New Branch</h1>
      <hr>
      <%= render 'form', branch: @branch %>

      <%= link_to 'Back', branches_path %>
    </div>
  </div>


  </div>

</div>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container margin-top">

  <div class="row">

    <div class="col-md-5 col-md-offset-3">
      <p>
        <strong>Id branch:</strong>
        <%= @branch.id_branch %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= @branch.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @branch.address %>
      </p>

      <%= link_to 'Edit', edit_branch_path(@branch) %> |
      <%= link_to 'Back', branches_path %>
    </div>
  </div>


  </div>

</div>