config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :branches
  resources :employees
  get 'home/index'
  devise_for :users

  root :to => 'home#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FooCorp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>

    <!-- <% if notice %>
      <p class="alert alert-success animated fadeIn"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger animated fadeIn"><%= alert %></p>
    <% end %> -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <%= link_to "Register", home_index_path, class: "nav-link" %>

      </li>

      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Employees", employees_path, class: "nav-link" %>

        </li>
        <li class="nav-item active">
          <%= link_to "Branches", branches_path, class: "nav-link" %>

        </li>
      <% end %>
      <!--<li class="nav-item">
        <a class="nav-link" href="#">Admin</a>
      </li>-->


    </ul>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <!-- <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | -->
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

  </div>
</nav>


    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- <script src="/javascript/script.js" crossorigin="anonymous" ></script> -->

    <!-- <script>
    $(function() {
      setTimeout(function() {
         $(".alert:visible").fadeOut();
      },2000);
    })
    </script> -->


  </body>
</html>